version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./custom_config.json:/etc/rabbitmq/custom_config.json
      - rabbitmq-data:/var/lib/rabbitmq

  python:
    image: python:3.7.3-alpine3.8
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: h3poteto
      RABBITMQ_PASSWORD: h3poteto
    command: /bin/sh
    links:
      - rabbitmq:rabbitmq
    working_dir: /var/opt/app/python
    volumes:
      - .:/var/opt/app

  node:
    image: node:12-alpine
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: h3poteto
      RABBITMQ_PASSWORD: h3poteto
      RABBITMQ_VHOST: /akira
    entrypoint: sh -c
    command: |
      "yarn install && \
      yarn run build && \
      node dist/index.js"
    links:
      - rabbitmq:rabbitmq
    working_dir: /var/opt/app/node
    volumes:
      - .:/var/opt/app

volumes:
  rabbitmq-data:
