version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./custom_config.json:/etc/rabbitmq/custom_config.json
      - rabbitmq-data:/var/lib/rabbitmq

  client:
    image: python:3.7.3-alpine3.8
    environment:
      RABBITMQ_USER: h3poteto
      RABBITMQ_PASSWORD: h3poteto
    command: /bin/sh
    links:
      - rabbitmq:rabbitmq
    working_dir: /var/opt/app
    volumes:
      - .:/var/opt/app

volumes:
  rabbitmq-data:
