version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./custom_config.json:/etc/rabbitmq/custom_config.json
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
